# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cmazakas/http_proto
    REF b0965f33473d2a2395af73a7629388d6306be239
    SHA512 381b8332860d3136d128dbc640ce91a1d40fda5807ec434812d6c3ec52584f4f22174bea648d4e58b2b75f19521f9f8c1648e72850e7fe2b97dcf2b8c9f37183
    HEAD_REF fix/vcpkg
)

vcpkg_replace_string("${SOURCE_PATH}/build/Jamfile"
    "import ../../config/checks/config"
    "import ../config/checks/config"
)
file(COPY "${CURRENT_INSTALLED_DIR}/share/boost-config/checks" DESTINATION "${SOURCE_PATH}/config")

vcpkg_replace_string("${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake"
    "\${BOOST_BUILD_INSTALLED_DIR}/share/boost-build/Jamroot.jam.in"
    "\${CMAKE_CURRENT_LIST_DIR}/Jamroot.jam.in"
)
include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
