# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cmazakas/buffers
    REF c9a1388cb4e35ac6cfd1f82a1b540bda3bc9e14b
    SHA512 2d04336e05226a630fc12f4d0c2e0eea3c9e08fe3033d07550758d746dafa73a3ef87f7a6a37c228f4ea559ec22886b6da5b077851c1b88c353b4e2542d0db48
    HEAD_REF jamfile-fixes
)

vcpkg_replace_string("${SOURCE_PATH}/build/Jamfile"
    "import ../../config/checks/config"
    "import ../config/checks/config"
)
file(COPY "${CURRENT_INSTALLED_DIR}/share/boost-config/checks" DESTINATION "${SOURCE_PATH}/config")
include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
