# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cmazakas/buffers
    REF ad55ec70a5c8d53b6bc395cdd59133ce4642b5ce
    SHA512 4e1959286f5646effd780720d84275825fa6467f954f8e826358b2108232d7785ecdc2e7f55bb0a7e94bfb01d14463fbaa92fccd6da564b00262e013fad6c9e0
    HEAD_REF fix/vcpkg
)

vcpkg_replace_string("${SOURCE_PATH}/build/Jamfile"
    "import ../../config/checks/config"
    "import ../config/checks/config"
)
file(COPY "${CURRENT_INSTALLED_DIR}/share/boost-config/checks" DESTINATION "${SOURCE_PATH}/config")
include(${CURRENT_HOST_INSTALLED_DIR}/share/boost-build/boost-modular-build.cmake)
boost_modular_build(SOURCE_PATH ${SOURCE_PATH})
include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
